# Generated by Django 4.2.5 on 2023-12-21 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('manuscript_id', models.AutoField(db_column='MANUSCRIPT_ID', primary_key=True, serialize=False)),
                ('manuscript_title', models.TextField(db_column='MANUSCRIPT_TITLE')),
                ('manuscript_authors', models.CharField(db_column='MANUSCRIPT_AUTHORS', max_length=255)),
                ('manuscript_url', models.TextField(db_column='MANUSCRIPT_URL')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='UPLOADED_AT')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manuscript',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(db_column='REPORT_ID', primary_key=True, serialize=False)),
                ('title_size', models.IntegerField(blank=True, db_column='TITLE_SIZE', null=True)),
                ('title_bold', models.IntegerField(blank=True, db_column='TITLE_BOLD', null=True)),
                ('author_size', models.IntegerField(blank=True, db_column='AUTHOR_SIZE', null=True)),
                ('author_bold', models.IntegerField(blank=True, db_column='AUTHOR_BOLD', null=True)),
                ('abs_background', models.IntegerField(blank=True, db_column='ABS_BACKGROUND', null=True)),
                ('abs_objectives', models.IntegerField(blank=True, db_column='ABS_OBJECTIVES', null=True)),
                ('abs_methods', models.IntegerField(blank=True, db_column='ABS_METHODS', null=True)),
                ('abs_result', models.IntegerField(blank=True, db_column='ABS_RESULT', null=True)),
                ('abs_conclusion', models.IntegerField(blank=True, db_column='ABS_CONCLUSION', null=True)),
                ('abs_keywords', models.IntegerField(blank=True, db_column='ABS_KEYWORDS', null=True)),
                ('abs_keywords_count', models.IntegerField(blank=True, db_column='ABS_KEYWORDS_COUNT', null=True)),
                ('abs_words_count', models.IntegerField(blank=True, db_column='ABS_WORDS_COUNT', null=True)),
                ('abs_sequential', models.IntegerField(blank=True, db_column='ABS_SEQUENTIAL', null=True)),
                ('str_header_1_format', models.IntegerField(blank=True, db_column='STR_HEADER_1_FORMAT', null=True)),
                ('str_header_1_fsizetitle', models.IntegerField(blank=True, db_column='STR_HEADER_1_FSIZETITLE', null=True)),
                ('str_header_1_fsizedetails', models.IntegerField(blank=True, db_column='STR_HEADER_1_FSIZEDETAILS', null=True)),
                ('str_header_1_ffam', models.IntegerField(blank=True, db_column='STR_HEADER_1_FFAM', null=True)),
                ('str_footer_1_format', models.IntegerField(blank=True, db_column='STR_FOOTER_1_FORMAT', null=True)),
                ('str_footer_1_fsize', models.IntegerField(blank=True, db_column='STR_FOOTER_1_FSIZE', null=True)),
                ('str_header_reg_format', models.IntegerField(blank=True, db_column='STR_HEADER_REG_FORMAT', null=True)),
                ('str_header_reg_fsize', models.IntegerField(blank=True, db_column='STR_HEADER_REG_FSIZE', null=True)),
                ('str_introduction', models.IntegerField(blank=True, db_column='STR_INTRODUCTION', null=True)),
                ('str_litrev', models.IntegerField(blank=True, db_column='STR_LITREV', null=True)),
                ('str_methods', models.IntegerField(blank=True, db_column='STR_METHODS', null=True)),
                ('str_result', models.IntegerField(blank=True, db_column='STR_RESULT', null=True)),
                ('str_discussion', models.IntegerField(blank=True, db_column='STR_DISCUSSION', null=True)),
                ('str_conclusion', models.IntegerField(blank=True, db_column='STR_CONCLUSION', null=True)),
                ('str_sequential', models.IntegerField(blank=True, db_column='STR_SEQUENTIAL', null=True)),
                ('add_table', models.IntegerField(blank=True, db_column='ADD_TABLE', null=True)),
                ('add_figure', models.IntegerField(blank=True, db_column='ADD_FIGURE', null=True)),
                ('ref_format', models.IntegerField(blank=True, db_column='REF_FORMAT', null=True)),
                ('ref_count', models.IntegerField(blank=True, db_column='REF_COUNT', null=True)),
                ('ref_used', models.IntegerField(blank=True, db_column='REF_USED', null=True)),
                ('manuscript', models.ForeignKey(db_column='MANUSCRIPT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='manuscripts.manuscript')),
            ],
            options={
                'db_table': 'report',
                'managed': True,
            },
        ),
    ]
